name: Detect drift

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  acls:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: 1.22.4
          cache: false

      - name: Detect ACL drift
        run: ./detect-drift.sh || true
        env:
          OAUTH_CLIENT_ID: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          OAUTH_CLIENT_SECRET: ${{ secrets.TS_OAUTH_SECRET }}
          TAILSCALE_TAILNET: ${{ secrets.TS_TAILNET }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          title: Reconcile ACL drift
          body: Automated drift-reconciliation changes
          labels: drift
